// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PostOfficeManagematAPI.Data;

#nullable disable

namespace PostOfficeManagematAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240605084509_Initial Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PostOfficeManagematAPI.Models.Domain.LetterBag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BagNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LettersCount")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("ShipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId");

                    b.ToTable("LetterBags");
                });

            modelBuilder.Entity("PostOfficeManagematAPI.Models.Domain.Parcel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DestinationCountry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParcelBagId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ParcelNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ParcelBagId");

                    b.ToTable("Parcels");
                });

            modelBuilder.Entity("PostOfficeManagematAPI.Models.Domain.ParcelBag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BagNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ShipmentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ShipmentId");

                    b.ToTable("ParcelBags");
                });

            modelBuilder.Entity("PostOfficeManagematAPI.Models.Domain.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Airport")
                        .HasColumnType("int");

                    b.Property<DateTime>("FlightDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShipmentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("PostOfficeManagematAPI.Models.Domain.LetterBag", b =>
                {
                    b.HasOne("PostOfficeManagematAPI.Models.Domain.Shipment", null)
                        .WithMany("LetterBags")
                        .HasForeignKey("ShipmentId");
                });

            modelBuilder.Entity("PostOfficeManagematAPI.Models.Domain.Parcel", b =>
                {
                    b.HasOne("PostOfficeManagematAPI.Models.Domain.ParcelBag", null)
                        .WithMany("Parcels")
                        .HasForeignKey("ParcelBagId");
                });

            modelBuilder.Entity("PostOfficeManagematAPI.Models.Domain.ParcelBag", b =>
                {
                    b.HasOne("PostOfficeManagematAPI.Models.Domain.Shipment", null)
                        .WithMany("ParcelBags")
                        .HasForeignKey("ShipmentId");
                });

            modelBuilder.Entity("PostOfficeManagematAPI.Models.Domain.ParcelBag", b =>
                {
                    b.Navigation("Parcels");
                });

            modelBuilder.Entity("PostOfficeManagematAPI.Models.Domain.Shipment", b =>
                {
                    b.Navigation("LetterBags");

                    b.Navigation("ParcelBags");
                });
#pragma warning restore 612, 618
        }
    }
}
